"""Genera scripts/finetune_dinov2_nose_v2.ipynb con el flujo completo:
1. Setup + GPU + deps (transformers pinned)
2. Bajar DogFaceNet
3. Subir + descomprimir test_photos
4. Cargar Grounding DINO + monkey patch
5. Crop de nariz: dataset + test
6. Liberar GPU + cargar DINOv2-large
7. Dataset + DataLoader (triplet)
8. Training loop 3 epochs
9. Eval contra test
10. (Opcional) guardar modelo
"""
import json
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "scripts" / "finetune_dinov2_nose_v2.ipynb"


def md(text):
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": [text],
    }


def code(text):
    return {
        "cell_type": "code",
        "metadata": {},
        "source": [text],
        "execution_count": None,
        "outputs": [],
    }


cells = [
    md(
        "# Fine-tuning DINOv2 nose print v2 (con crop preciso)\n"
        "\n"
        "Pipeline completo:\n"
        "1. Setup GPU + deps con `transformers==4.41.2` (compat Grounding DINO)\n"
        "2. Bajar DogFaceNet (1393 perros, 8363 fotos)\n"
        "3. Subir tu zip `nose_print_test_photos.zip` al panel Files\n"
        "4. Cargar Grounding DINO + monkey patch BertModel\n"
        "5. Crop de nariz: dataset DogFaceNet + tus fotos test\n"
        "6. Liberar GPU + cargar DINOv2-large\n"
        "7. Dataset Triplet + DataLoader\n"
        "8. Training 3 epochs (~30 min en T4)\n"
        "9. Eval: same/cross/separación\n"
        "10. (Opcional) guardar modelo\n"
        "\n"
        "**Correr de arriba a abajo, una celda por vez con Shift+Enter**.\n"
        "Si una celda falla, no avanzar hasta resolverla.\n"
    ),

    md(
        "## 1. Setup GPU + deps\n"
        "\n"
        "⚠️ **Importante**: instalar `groundingdino-py` puede reinstalar torch en versión CPU. "
        "Esta celda instala TODO en orden + fuerza torch con CUDA al final para evitar el bug.\n"
        "\n"
        "Si después de correr ves `CUDA: False`, reiniciá el runtime "
        "(Runtime > Restart session) y corré la celda de nuevo.\n"
    ),
    code(
        "# Verificar GPU + instalar deps con versiones compatibles.\n"
        "# transformers==4.41.2 evita el bug get_head_mask con groundingdino.\n"
        "# torch+CUDA se reinstala AL FINAL para asegurar que groundingdino-py\n"
        "# no haya pisado torch con la versión CPU-only.\n"
        "!nvidia-smi | head -15\n"
        "!pip install -q transformers==4.41.2 timm==0.9.16 supervision groundingdino-py tqdm\n"
        "# Forzar torch con CUDA 12.1 (T4 compatible) en última posición\n"
        "!pip install -q torch==2.4.0 torchvision==0.19.0 --index-url https://download.pytorch.org/whl/cu121\n"
        "\n"
        "import torch\n"
        "print('\\nPyTorch:', torch.__version__)\n"
        "print('CUDA disponible:', torch.cuda.is_available())\n"
        "if torch.cuda.is_available():\n"
        "    print('GPU:', torch.cuda.get_device_name(0))\n"
        "    print('CUDA build:', torch.version.cuda)\n"
        "else:\n"
        "    print('⚠️ CUDA NO disponible. Reiniciá el runtime con Runtime > Restart session '\n"
        "          'y volvé a correr esta celda.')\n"
    ),

    md("## 2. Descargar DogFaceNet\n"),
    code(
        "import os\n"
        "%cd /content\n"
        "!mkdir -p dogfacenet\n"
        "\n"
        "if not os.path.exists('/content/dogfacenet/after_4_bis'):\n"
        "    !wget -q --show-progress -O dogfacenet/images.zip \\\n"
        "      https://github.com/GuillaumeMougeot/DogFaceNet/releases/download/dataset/DogFaceNet_Dataset_224_1.zip\n"
        "    !wget -q -O dogfacenet/classes_train.txt \\\n"
        "      https://github.com/GuillaumeMougeot/DogFaceNet/releases/download/dataset/classes_train.txt\n"
        "    !wget -q -O dogfacenet/classes_test.txt \\\n"
        "      https://github.com/GuillaumeMougeot/DogFaceNet/releases/download/dataset/classes_test.txt\n"
        "    !unzip -oq dogfacenet/images.zip -d dogfacenet/\n"
        "    print('Dataset bajado y descomprimido')\n"
        "else:\n"
        "    print('Dataset ya estaba presente')\n"
        "\n"
        "!ls /content/dogfacenet | head -5\n"
        "!find /content/dogfacenet/after_4_bis -type f | wc -l\n"
    ),

    md(
        "## 3. Subir tus fotos test\n"
        "\n"
        "1. **En Windows PowerShell**, asegurate de tener el zip actualizado:\n"
        "```powershell\n"
        "Compress-Archive -Path \"_pending\\nose_print_test_photos\\*\" "
        "-DestinationPath \"_pending\\nose_print_test_photos.zip\" -Force\n"
        "```\n"
        "\n"
        "2. **En Colab**, panel izquierdo Files → arrastrar `nose_print_test_photos.zip`. "
        "Esperar que la barra azul desaparezca.\n"
        "\n"
        "3. **Correr la celda siguiente** que descomprime + aplana estructura.\n"
    ),
    code(
        "import os, shutil\n"
        "\n"
        "ZIP = '/content/nose_print_test_photos.zip'\n"
        "DST = '/content/test_photos'\n"
        "\n"
        "if not os.path.exists(ZIP):\n"
        "    raise FileNotFoundError(f'No encuentro {ZIP}. Subilo al panel Files antes de correr.')\n"
        "\n"
        "if os.path.exists(DST):\n"
        "    shutil.rmtree(DST)\n"
        "\n"
        "!unzip -oq {ZIP} -d {DST}\n"
        "\n"
        "# Si Compress-Archive metió un nivel extra de carpeta, aplanar\n"
        "inner = os.path.join(DST, 'nose_print_test_photos')\n"
        "if os.path.isdir(inner):\n"
        "    for item in os.listdir(inner):\n"
        "        shutil.move(os.path.join(inner, item), DST + '/')\n"
        "    os.rmdir(inner)\n"
        "    print('Estructura aplanada')\n"
        "\n"
        "print('Carpetas:')\n"
        "!ls /content/test_photos\n"
        "print('\\nTotal fotos:')\n"
        "!find /content/test_photos -type f \\( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.webp' \\) | wc -l\n"
    ),

    md("## 4. Cargar Grounding DINO\n"),
    code(
        "import os\n"
        "os.makedirs('/content/groundingdino_weights', exist_ok=True)\n"
        "if not os.path.exists('/content/groundingdino_weights/groundingdino_swint_ogc.pth'):\n"
        "    !wget -q --show-progress -O /content/groundingdino_weights/groundingdino_swint_ogc.pth \\\n"
        "      https://github.com/IDEA-Research/GroundingDINO/releases/download/v0.1.0-alpha/groundingdino_swint_ogc.pth\n"
        "    print('Pesos bajados')\n"
        "else:\n"
        "    print('Pesos ya presentes')\n"
    ),
    code(
        "# Monkey patch BertModel.get_head_mask (bug de transformers + groundingdino)\n"
        "from transformers import BertModel as _BertModel\n"
        "if not hasattr(_BertModel, 'get_head_mask'):\n"
        "    from transformers.modeling_utils import PreTrainedModel\n"
        "    if hasattr(PreTrainedModel, 'get_head_mask'):\n"
        "        _BertModel.get_head_mask = PreTrainedModel.get_head_mask\n"
        "        print('Monkey patch BertModel.get_head_mask aplicado')\n"
        "    else:\n"
        "        print('No se pudo aplicar monkey patch (transformers <4.41 OK)')\n"
        "\n"
        "import glob, torch\n"
        "from PIL import Image\n"
        "from groundingdino.util.inference import load_model, predict, load_image\n"
        "\n"
        "device = 'cuda' if torch.cuda.is_available() else 'cpu'\n"
        "\n"
        "config_candidates = glob.glob(\n"
        "    '/usr/local/lib/python*/dist-packages/groundingdino/config/GroundingDINO_SwinT_OGC.py'\n"
        ")\n"
        "if not config_candidates:\n"
        "    raise FileNotFoundError('No se encontró el config')\n"
        "CONFIG_PATH = config_candidates[0]\n"
        "print('Config:', CONFIG_PATH)\n"
        "\n"
        "dino = load_model(\n"
        "    CONFIG_PATH,\n"
        "    '/content/groundingdino_weights/groundingdino_swint_ogc.pth'\n"
        ")\n"
        "print('Grounding DINO cargado.')\n"
    ),

    md("## 5. Crop de nariz\n\nProbamos primero con 1 imagen sample.\n"),
    code(
        "PROMPT = 'dog nose . cat nose . pet nose . animal nose'\n"
        "\n"
        "def crop_nose(img_path, padding=0.25, fallback_center=True):\n"
        "    try:\n"
        "        image_source, image_tensor = load_image(img_path)\n"
        "        boxes, logits, phrases = predict(\n"
        "            model=dino, image=image_tensor,\n"
        "            caption=PROMPT, box_threshold=0.30, text_threshold=0.25\n"
        "        )\n"
        "        if len(boxes) > 0:\n"
        "            best = boxes[logits.argmax().item()]\n"
        "            cx, cy, w, h = best.tolist()\n"
        "            ih, iw = image_source.shape[:2]\n"
        "            cx, cy = cx * iw, cy * ih\n"
        "            w, h = w * iw * (1 + padding), h * ih * (1 + padding)\n"
        "            side = max(w, h)\n"
        "            x1 = max(0, int(cx - side / 2))\n"
        "            y1 = max(0, int(cy - side / 2))\n"
        "            x2 = min(iw, int(cx + side / 2))\n"
        "            y2 = min(ih, int(cy + side / 2))\n"
        "            return Image.fromarray(image_source[y1:y2, x1:x2]), 'detected'\n"
        "    except Exception as e:\n"
        "        print('crop error:', e)\n"
        "    if fallback_center:\n"
        "        img = Image.open(img_path).convert('RGB')\n"
        "        w, h = img.size\n"
        "        side = min(w, h)\n"
        "        l = (w - side) // 2\n"
        "        t = (h - side) // 2\n"
        "        return img.crop((l, t, l + side, t + side)), 'fallback'\n"
        "    return None, 'failed'\n"
        "\n"
        "# Test sample\n"
        "sample = '/content/dogfacenet/after_4_bis/139/139.0.jpg'\n"
        "crop, status = crop_nose(sample)\n"
        "print(f'Test sample: {status}, size {crop.size if crop else None}')\n"
        "if crop:\n"
        "    crop.resize((224,224)).save('/tmp/sample_nose.jpg')\n"
        "    print('Guardado en /tmp/sample_nose.jpg → revisalo en panel Files')\n"
    ),

    md(
        "## 6. Procesar DogFaceNet (8.363 imgs) + tus fotos test\n"
        "\nTarda ~10-15 min porque procesa cada imagen con Grounding DINO.\n"
    ),
    code(
        "import os, shutil\n"
        "from tqdm import tqdm\n"
        "\n"
        "SRC = '/content/dogfacenet/after_4_bis'\n"
        "DST = '/content/dogfacenet_nose'\n"
        "\n"
        "if os.path.exists(DST):\n"
        "    shutil.rmtree(DST)\n"
        "os.makedirs(DST)\n"
        "\n"
        "stats = {'detected': 0, 'fallback': 0, 'failed': 0}\n"
        "\n"
        "for dog_id in tqdm(os.listdir(SRC), desc='Perros'):\n"
        "    src_dog = os.path.join(SRC, dog_id)\n"
        "    if not os.path.isdir(src_dog):\n"
        "        continue\n"
        "    dst_dog = os.path.join(DST, dog_id)\n"
        "    os.makedirs(dst_dog, exist_ok=True)\n"
        "    for fname in os.listdir(src_dog):\n"
        "        if not fname.lower().endswith(('.jpg', '.jpeg', '.png')):\n"
        "            continue\n"
        "        crop, status = crop_nose(os.path.join(src_dog, fname))\n"
        "        stats[status] += 1\n"
        "        if crop:\n"
        "            crop.resize((224, 224)).save(os.path.join(dst_dog, fname), quality=92)\n"
        "\n"
        "total = sum(stats.values())\n"
        "print('\\n=== Stats DogFaceNet ===')\n"
        "print(f'Total: {total}')\n"
        "print(f'Detectados con DINO: {stats[\"detected\"]} ({100*stats[\"detected\"]/total:.1f}%)')\n"
        "print(f'Fallback center crop: {stats[\"fallback\"]} ({100*stats[\"fallback\"]/total:.1f}%)')\n"
        "print(f'Fallidos: {stats[\"failed\"]}')\n"
    ),
    code(
        "import os, shutil\n"
        "from tqdm import tqdm\n"
        "\n"
        "SRC = '/content/test_photos'\n"
        "DST = '/content/test_photos_nose'\n"
        "\n"
        "if os.path.exists(DST):\n"
        "    shutil.rmtree(DST)\n"
        "os.makedirs(DST)\n"
        "\n"
        "for pet_dir in os.listdir(SRC):\n"
        "    src = os.path.join(SRC, pet_dir)\n"
        "    if not os.path.isdir(src):\n"
        "        continue\n"
        "    dst = os.path.join(DST, pet_dir)\n"
        "    os.makedirs(dst, exist_ok=True)\n"
        "    for fname in tqdm(os.listdir(src), desc=pet_dir):\n"
        "        if not fname.lower().endswith(('.jpg', '.jpeg', '.png', '.webp')):\n"
        "            continue\n"
        "        crop, _ = crop_nose(os.path.join(src, fname))\n"
        "        if crop:\n"
        "            crop.resize((224, 224)).save(os.path.join(dst, fname), quality=92)\n"
        "\n"
        "print('\\nTotal fotos test croppeadas:')\n"
        "!find /content/test_photos_nose -type f | wc -l\n"
    ),

    md("## 7. Liberar GPU + cargar DINOv2-large\n"),
    code(
        "# Liberar Grounding DINO de la GPU antes de cargar DINOv2-large\n"
        "import torch, gc\n"
        "try:\n"
        "    del dino\n"
        "except Exception:\n"
        "    pass\n"
        "gc.collect()\n"
        "torch.cuda.empty_cache()\n"
        "print('GPU memory:', torch.cuda.memory_allocated() / 1e9, 'GB')\n"
        "\n"
        "# Cargar DINOv2-large\n"
        "MODEL_ID = 'facebook/dinov2-large'\n"
        "from transformers import AutoModel, AutoImageProcessor\n"
        "\n"
        "device = 'cuda' if torch.cuda.is_available() else 'cpu'\n"
        "\n"
        "model = AutoModel.from_pretrained(MODEL_ID).to(device)\n"
        "processor = AutoImageProcessor.from_pretrained(MODEL_ID)\n"
        "print('DINOv2-large cargado.')\n"
        "print('Param count:', sum(p.numel() for p in model.parameters()) / 1e6, 'M')\n"
        "\n"
        "def get_embedding(model, pixel_tensor):\n"
        "    \"\"\"CLS embedding L2-normalizado.\"\"\"\n"
        "    out = model(pixel_values=pixel_tensor)\n"
        "    cls = out.last_hidden_state[:, 0]\n"
        "    return torch.nn.functional.normalize(cls, dim=-1)\n"
    ),

    md("## 8. Dataset + DataLoader (Triplet)\n"),
    code(
        "import os, random\n"
        "from PIL import Image\n"
        "from torch.utils.data import Dataset, DataLoader\n"
        "from torchvision import transforms\n"
        "\n"
        "DOGFACENET_DIR = '/content/dogfacenet_nose'\n"
        "IMAGE_SIZE = 224\n"
        "\n"
        "train_transform = transforms.Compose([\n"
        "    transforms.Resize((IMAGE_SIZE + 16, IMAGE_SIZE + 16)),\n"
        "    transforms.RandomCrop(IMAGE_SIZE),\n"
        "    transforms.RandomHorizontalFlip(p=0.5),\n"
        "    transforms.ColorJitter(brightness=0.1, contrast=0.1, saturation=0.1),\n"
        "    transforms.ToTensor(),\n"
        "    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])\n"
        "])\n"
        "\n"
        "eval_transform = transforms.Compose([\n"
        "    transforms.Resize((IMAGE_SIZE, IMAGE_SIZE)),\n"
        "    transforms.ToTensor(),\n"
        "    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])\n"
        "])\n"
        "\n"
        "def get_dogfacenet_grouped(root, min_photos=2):\n"
        "    groups = {}\n"
        "    for dog_id in os.listdir(root):\n"
        "        dog_path = os.path.join(root, dog_id)\n"
        "        if not os.path.isdir(dog_path):\n"
        "            continue\n"
        "        photos = [os.path.join(dog_path, f) for f in os.listdir(dog_path)\n"
        "                  if f.lower().endswith(('.jpg', '.jpeg', '.png'))]\n"
        "        if len(photos) >= min_photos:\n"
        "            groups[dog_id] = photos\n"
        "    return groups\n"
        "\n"
        "class TripletDataset(Dataset):\n"
        "    def __init__(self, groups, transform):\n"
        "        self.groups = groups\n"
        "        self.dog_ids = list(groups.keys())\n"
        "        self.transform = transform\n"
        "        self.all_samples = [(d, f) for d, files in groups.items() for f in files]\n"
        "\n"
        "    def __len__(self):\n"
        "        return len(self.all_samples)\n"
        "\n"
        "    def __getitem__(self, idx):\n"
        "        anchor_dog, anchor_path = self.all_samples[idx]\n"
        "        same = [f for f in self.groups[anchor_dog] if f != anchor_path]\n"
        "        pos_path = random.choice(same)\n"
        "        other_dog = random.choice([d for d in self.dog_ids if d != anchor_dog])\n"
        "        neg_path = random.choice(self.groups[other_dog])\n"
        "        try:\n"
        "            anchor = self.transform(Image.open(anchor_path).convert('RGB'))\n"
        "            positive = self.transform(Image.open(pos_path).convert('RGB'))\n"
        "            negative = self.transform(Image.open(neg_path).convert('RGB'))\n"
        "            return anchor, positive, negative\n"
        "        except Exception:\n"
        "            return self.__getitem__((idx + 1) % len(self))\n"
        "\n"
        "pet_groups = get_dogfacenet_grouped(DOGFACENET_DIR)\n"
        "print(f'Perros únicos: {len(pet_groups)}')\n"
        "print(f'Total fotos: {sum(len(v) for v in pet_groups.values())}')\n"
        "\n"
        "BATCH_SIZE = 8\n"
        "dataset = TripletDataset(pet_groups, train_transform)\n"
        "loader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=2, pin_memory=True)\n"
        "print(f'Dataset: {len(dataset)} muestras, {len(loader)} batches de {BATCH_SIZE}')\n"
    ),

    md("## 9. Training (3 epochs)\n"),
    code(
        "import torch.nn.functional as F\n"
        "from torch.optim import AdamW\n"
        "from tqdm import tqdm\n"
        "\n"
        "# Hiperparámetros\n"
        "EPOCHS = 3\n"
        "LR = 1e-5\n"
        "MARGIN = 0.3\n"
        "NUM_TRAINABLE_LAYERS = 2  # solo últimos 2 bloques + LayerNorm\n"
        "\n"
        "# Freeze layers excepto las últimas\n"
        "for p in model.parameters():\n"
        "    p.requires_grad = False\n"
        "\n"
        "trainable_layer_idx = list(range(\n"
        "    len(model.encoder.layer) - NUM_TRAINABLE_LAYERS,\n"
        "    len(model.encoder.layer)\n"
        "))\n"
        "for i in trainable_layer_idx:\n"
        "    for p in model.encoder.layer[i].parameters():\n"
        "        p.requires_grad = True\n"
        "for p in model.layernorm.parameters():\n"
        "    p.requires_grad = True\n"
        "\n"
        "trainable = [p for p in model.parameters() if p.requires_grad]\n"
        "print(f'Trainable params: {sum(p.numel() for p in trainable) / 1e6:.1f} M')\n"
        "\n"
        "optimizer = AdamW(trainable, lr=LR, weight_decay=0.01)\n"
        "\n"
        "model.train()\n"
        "for epoch in range(EPOCHS):\n"
        "    epoch_loss = 0.0\n"
        "    pbar = tqdm(loader, desc=f'Epoch {epoch+1}/{EPOCHS}')\n"
        "    for anchor, positive, negative in pbar:\n"
        "        anchor = anchor.to(device)\n"
        "        positive = positive.to(device)\n"
        "        negative = negative.to(device)\n"
        "\n"
        "        emb_a = get_embedding(model, anchor)\n"
        "        emb_p = get_embedding(model, positive)\n"
        "        emb_n = get_embedding(model, negative)\n"
        "\n"
        "        loss = F.triplet_margin_loss(emb_a, emb_p, emb_n, margin=MARGIN, p=2)\n"
        "\n"
        "        optimizer.zero_grad()\n"
        "        loss.backward()\n"
        "        optimizer.step()\n"
        "\n"
        "        epoch_loss += loss.item()\n"
        "        pbar.set_postfix(loss=f'{loss.item():.4f}')\n"
        "    print(f'Epoch {epoch+1}: avg loss = {epoch_loss/len(loader):.4f}')\n"
        "\n"
        "print('\\nTraining completo.')\n"
    ),

    md("## 10. Evaluación contra fotos test\n"),
    code(
        "from itertools import combinations\n"
        "import numpy as np\n"
        "import os\n"
        "from PIL import Image\n"
        "\n"
        "TEST_DIR = '/content/test_photos_nose'\n"
        "\n"
        "def cosine_sim(a, b):\n"
        "    a, b = a.flatten(), b.flatten()\n"
        "    return float(np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b) + 1e-12))\n"
        "\n"
        "def extract_embedding_eval(model, img_path):\n"
        "    img = Image.open(img_path).convert('RGB')\n"
        "    w, h = img.size\n"
        "    crop_size = min(w, h)\n"
        "    left = (w - crop_size) // 2\n"
        "    top = (h - crop_size) // 2\n"
        "    img = img.crop((left, top, left + crop_size, top + crop_size))\n"
        "    tensor = eval_transform(img).unsqueeze(0).to(device)\n"
        "    with torch.no_grad():\n"
        "        emb = get_embedding(model, tensor)\n"
        "    return emb.cpu().numpy().squeeze()\n"
        "\n"
        "# Recolectar pets test\n"
        "pets_test = {}\n"
        "for pet_dir in os.listdir(TEST_DIR):\n"
        "    full = os.path.join(TEST_DIR, pet_dir)\n"
        "    if os.path.isdir(full):\n"
        "        photos = [os.path.join(full, f) for f in os.listdir(full)\n"
        "                  if f.lower().endswith(('.jpg', '.jpeg', '.png', '.webp'))]\n"
        "        if len(photos) >= 2:\n"
        "            pets_test[pet_dir] = photos\n"
        "\n"
        "print(f'Mascotas test: {len(pets_test)}')\n"
        "print(f'Total fotos: {sum(len(v) for v in pets_test.values())}')\n"
        "\n"
        "model.eval()\n"
        "embeddings = {}\n"
        "for pet_name, photos in pets_test.items():\n"
        "    embs = []\n"
        "    for p in tqdm(photos, desc=pet_name):\n"
        "        embs.append(extract_embedding_eval(model, p))\n"
        "    embeddings[pet_name] = embs\n"
        "\n"
        "same_sims, cross_sims = [], []\n"
        "for pet, embs in embeddings.items():\n"
        "    for i, j in combinations(range(len(embs)), 2):\n"
        "        same_sims.append(cosine_sim(embs[i], embs[j]))\n"
        "\n"
        "pets_list = list(embeddings.keys())\n"
        "for pa, pb in combinations(pets_list, 2):\n"
        "    for ea in embeddings[pa]:\n"
        "        for eb in embeddings[pb]:\n"
        "            cross_sims.append(cosine_sim(ea, eb))\n"
        "\n"
        "same_mean = float(np.mean(same_sims))\n"
        "cross_mean = float(np.mean(cross_sims))\n"
        "separation = same_mean - cross_mean\n"
        "\n"
        "print('\\n' + '=' * 60)\n"
        "print('EVAL FINE-TUNED v2 (con crop preciso de nariz)')\n"
        "print('=' * 60)\n"
        "print(f'Pares same-pet:  {len(same_sims)}')\n"
        "print(f'Pares cross-pet: {len(cross_sims)}')\n"
        "print(f'Same-pet mean:   {same_mean:.4f}')\n"
        "print(f'Cross-pet mean:  {cross_mean:.4f}')\n"
        "print(f'Separación:      {separation:.4f}')\n"
        "print('=' * 60)\n"
        "print('vs Baseline DINOv2-large (cara entera, sin entrenar): same=0.718 cross=0.272 sep=0.445')\n"
        "print(f'\\nDELTA vs baseline: {(\"+\" if separation > 0.445 else \"\")}{separation - 0.445:+.3f}')\n"
        "if separation > 0.80:\n"
        "    print('[EXCELENTE] Production-grade')\n"
        "elif separation > 0.65:\n"
        "    print('[BUENO] Production OK con threshold 0.55')\n"
        "elif separation > 0.50:\n"
        "    print('[OK] Mejora modesta, conseguir más individuos')\n"
        "else:\n"
        "    print('[POBRE] El crop preciso no movió la aguja - hace falta data por individuo (refugios)')\n"
    ),

    md("## 11. (Opcional) Guardar modelo\n"),
    code(
        "OUTPUT_PATH = '/content/dinov2_large_nose_v2_finetuned.pt'\n"
        "\n"
        "torch.save({\n"
        "    'model_state_dict': model.state_dict(),\n"
        "    'model_id': MODEL_ID,\n"
        "    'num_trainable_layers': NUM_TRAINABLE_LAYERS,\n"
        "    'epochs': EPOCHS,\n"
        "    'lr': LR,\n"
        "    'margin': MARGIN,\n"
        "    'eval_separation': separation,\n"
        "    'eval_same_mean': same_mean,\n"
        "    'eval_cross_mean': cross_mean,\n"
        "    'preprocessing': 'grounding_dino_nose_crop',\n"
        "}, OUTPUT_PATH)\n"
        "\n"
        "import os\n"
        "size_mb = os.path.getsize(OUTPUT_PATH) / 1024 / 1024\n"
        "print(f'Modelo guardado: {OUTPUT_PATH} ({size_mb:.0f} MB)')\n"
        "print('Para descargar: panel Files → click derecho en el archivo → Download')\n"
    ),
]

notebook = {
    "cells": cells,
    "metadata": {
        "colab": {
            "name": "finetune_dinov2_nose_v2",
            "provenance": [],
            "gpuType": "T4",
        },
        "kernelspec": {
            "display_name": "Python 3",
            "name": "python3",
        },
        "language_info": {
            "name": "python",
        },
        "accelerator": "GPU",
    },
    "nbformat": 4,
    "nbformat_minor": 0,
}

with open(OUT, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)

print(f"OK -> {OUT} ({OUT.stat().st_size} bytes, {len(cells)} cells)")
