// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Use 'any' for database generic to avoid RejectExcessProperties errors
// when the generated types.ts is out of sync with the actual DB schema.
// This is safe because PostgREST validates columns server-side.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const supabase = createClient<any>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    // storageKey especifico evita colisiones con otros clients Supabase en la
    // misma pagina (antes generaba "Lock was stolen" warnings masivos).
    storageKey: 'pf-auth-v1',
    persistSession: true,
    autoRefreshToken: true,
    // Evita que Supabase intente usar el Web Locks API (causa race conditions
    // con multiples tabs); confiamos en localStorage para sincronizar sesion.
    lock: (_name, _acquireTimeout, fn) => fn(),
  },
  global: {
    headers: { 'x-client-info': 'paw-friend-web' },
    fetch: (url: RequestInfo | URL, options?: RequestInit) => {
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), 15000);
      const signal = options?.signal ? options.signal : controller.signal;
      return fetch(url, { ...options, signal }).finally(() => clearTimeout(timeoutId));
    },
  },
});
